// Auto-generated catalog of music videos (pre-2000), one entry per video.
// id = YouTube video id. album/label feed the on-screen title card.
// tags drive the channel lineup and the taste model; era tags ("80s"/"90s") are for display.
window.CATALOG = [
  {"id": "W8r-tXRLazs", "artist": "The Buggles", "title": "Video Killed the Radio Star", "album": "The Age of Plastic", "label": "Island", "year": 1979, "tags": ["80s", "new-wave", "pop"]},
  {"id": "djV11Xbc914", "artist": "a-ha", "title": "Take On Me", "album": "Hunting High and Low", "label": "Warner Bros.", "year": 1985, "tags": ["80s", "synth-pop", "pop"]},
  {"id": "sOnqjkJTMaA", "artist": "Michael Jackson", "title": "Thriller", "album": "Thriller", "label": "Epic", "year": 1983, "tags": ["80s", "pop", "r&b"]},
  {"id": "Zi_XLOBDo_Y", "artist": "Michael Jackson", "title": "Billie Jean", "album": "Thriller", "label": "Epic", "year": 1983, "tags": ["80s", "pop", "r&b"]},
  {"id": "oRdxUFDoQe0", "artist": "Michael Jackson", "title": "Beat It", "album": "Thriller", "label": "Epic", "year": 1983, "tags": ["80s", "pop", "rock"]},
  {"id": "79fzeNUqQbQ", "artist": "Madonna", "title": "Like a Prayer", "album": "Like a Prayer", "label": "Sire", "year": 1989, "tags": ["80s", "pop"]},
  {"id": "6p-lDYPR2P8", "artist": "Madonna", "title": "Material Girl", "album": "Like a Virgin", "label": "Sire", "year": 1985, "tags": ["80s", "pop"]},
  {"id": "UG3VcCAlUgE", "artist": "Prince", "title": "When Doves Cry", "album": "Purple Rain", "label": "Warner Bros.", "year": 1984, "tags": ["80s", "pop", "funk"]},
  {"id": "EAJuqv20DfM", "artist": "Peter Gabriel", "title": "Sledgehammer", "album": "So", "label": "Geffen", "year": 1986, "tags": ["80s", "art-rock", "pop"]},
  {"id": "wTP2RUD_cL0", "artist": "Dire Straits", "title": "Money for Nothing", "album": "Brothers in Arms", "label": "Warner Bros.", "year": 1985, "tags": ["80s", "rock"]},
  {"id": "5IsSpAOD6K8", "artist": "Talking Heads", "title": "Once in a Lifetime", "album": "Remain in Light", "label": "Sire", "year": 1981, "tags": ["80s", "new-wave", "art-rock"]},
  {"id": "qeMFqkcPYcg", "artist": "Eurythmics", "title": "Sweet Dreams (Are Made of This)", "album": "Sweet Dreams (Are Made of This)", "label": "RCA", "year": 1983, "tags": ["80s", "synth-pop", "new-wave"]},
  {"id": "PIb6AZdTr-A", "artist": "Cyndi Lauper", "title": "Girls Just Want to Have Fun", "album": "She's So Unusual", "label": "Portrait", "year": 1983, "tags": ["80s", "pop"]},
  {"id": "aGCdLKXNF3w", "artist": "Tears for Fears", "title": "Everybody Wants to Rule the World", "album": "Songs from the Big Chair", "label": "Mercury", "year": 1985, "tags": ["80s", "synth-pop", "pop"]},
  {"id": "oJL-lCzEXgI", "artist": "Duran Duran", "title": "Hungry Like the Wolf", "album": "Rio", "label": "Capitol", "year": 1982, "tags": ["80s", "new-wave", "pop"]},
  {"id": "OMOGaugKpzs", "artist": "The Police", "title": "Every Breath You Take", "album": "Synchronicity", "label": "A&M", "year": 1983, "tags": ["80s", "rock", "pop"]},
  {"id": "ynkaGd_zGwE", "artist": "Whitney Houston", "title": "I Wanna Dance with Somebody", "album": "Whitney", "label": "Arista", "year": 1987, "tags": ["80s", "pop", "r&b"]},
  {"id": "lMGaiSqOp58", "artist": "Bon Jovi", "title": "Livin' on a Prayer", "album": "Slippery When Wet", "label": "Mercury", "year": 1986, "tags": ["80s", "rock", "hair-metal"]},
  {"id": "SwYN7mTi6HM", "artist": "Van Halen", "title": "Jump", "album": "1984", "label": "Warner Bros.", "year": 1984, "tags": ["80s", "rock", "hair-metal"]},
  {"id": "j_QLzthSkfM", "artist": "Devo", "title": "Whip It", "album": "Freedom of Choice", "label": "Warner Bros.", "year": 1980, "tags": ["80s", "new-wave", "art-rock"]},
  {"id": "JmcA9LIIXWw", "artist": "Culture Club", "title": "Karma Chameleon", "album": "Colour by Numbers", "label": "Virgin", "year": 1983, "tags": ["80s", "pop", "new-wave"]},
  {"id": "FTQbiNvZqaY", "artist": "Toto", "title": "Africa", "album": "Toto IV", "label": "Columbia", "year": 1982, "tags": ["80s", "rock", "pop"]},
  {"id": "Uj2K3rerzT4", "artist": "Wham!", "title": "Wake Me Up Before You Go-Go", "album": "Make It Big", "label": "Columbia", "year": 1984, "tags": ["80s", "pop"]},
  {"id": "d7VrQod3ad8", "artist": "Bonnie Tyler", "title": "Total Eclipse of the Heart", "album": "Faster Than the Speed of Night", "label": "Columbia", "year": 1983, "tags": ["80s", "pop", "rock"]},
  {"id": "GHhD4PD75zY", "artist": "Herbie Hancock", "title": "Rockit", "album": "Future Shock", "label": "Columbia", "year": 1983, "tags": ["80s", "electronic", "funk"]},
  {"id": "dQw4w9WgXcQ", "artist": "Rick Astley", "title": "Never Gonna Give You Up", "album": "Whenever You Need Somebody", "label": "RCA", "year": 1987, "tags": ["80s", "pop"]},
  {"id": "OAwaNWGLM0c", "artist": "Janet Jackson", "title": "Rhythm Nation", "album": "Rhythm Nation 1814", "label": "A&M", "year": 1989, "tags": ["80s", "pop", "r&b"]},
  {"id": "129kuDCQtHs", "artist": "Bruce Springsteen", "title": "Dancing in the Dark", "album": "Born in the U.S.A.", "label": "Columbia", "year": 1984, "tags": ["80s", "rock"]},
  {"id": "4xmckWVPRaI", "artist": "Twisted Sister", "title": "We're Not Gonna Take It", "album": "Stay Hungry", "label": "Atlantic", "year": 1984, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "XZVpR3Pk-r8", "artist": "Soft Cell", "title": "Tainted Love", "album": "Non-Stop Erotic Cabaret", "label": "Sire", "year": 1981, "tags": ["80s", "synth-pop", "new-wave"]},
  {"id": "F93ywiGMDnQ", "artist": "INXS", "title": "Need You Tonight", "album": "Kick", "label": "Atlantic", "year": 1987, "tags": ["80s", "rock", "pop"]},
  {"id": "6Cs3Pvmmv0E", "artist": "George Michael", "title": "Faith", "album": "Faith", "label": "Columbia", "year": 1987, "tags": ["80s", "pop"]},
  {"id": "fJ9rUzIMcZQ", "artist": "Queen", "title": "Bohemian Rhapsody", "album": "A Night at the Opera", "label": "Elektra", "year": 1975, "tags": ["80s", "rock"]},
  {"id": "hTWKbfoikeg", "artist": "Nirvana", "title": "Smells Like Teen Spirit", "album": "Nevermind", "label": "DGC", "year": 1991, "tags": ["90s", "grunge", "rock", "alternative"]},
  {"id": "n6P0SitRwy8", "artist": "Nirvana", "title": "Heart-Shaped Box", "album": "In Utero", "label": "DGC", "year": 1993, "tags": ["90s", "grunge", "rock", "alternative"]},
  {"id": "vabnZ9-ex7o", "artist": "Nirvana", "title": "Come As You Are", "album": "Nevermind", "label": "DGC", "year": 1992, "tags": ["90s", "grunge", "rock", "alternative"]},
  {"id": "JNZezhUkOSk", "artist": "Pearl Jam", "title": "Jeremy", "album": "Ten", "label": "Epic", "year": 1992, "tags": ["90s", "grunge", "rock", "alternative"]},
  {"id": "9EiP8ROD3gc", "artist": "Soundgarden", "title": "Black Hole Sun", "album": "Superunknown", "label": "A&M", "year": 1994, "tags": ["90s", "grunge", "rock", "alternative"]},
  {"id": "TAqZb52sgpU", "artist": "Alice in Chains", "title": "Man in the Box", "album": "Facelift", "label": "Columbia", "year": 1991, "tags": ["90s", "grunge", "rock", "metal"]},
  {"id": "V5UOC0C0x8Q", "artist": "Stone Temple Pilots", "title": "Plush", "album": "Core", "label": "Atlantic", "year": 1993, "tags": ["90s", "grunge", "rock", "alternative"]},
  {"id": "4aeETEoNfOg", "artist": "The Smashing Pumpkins", "title": "1979", "album": "Mellon Collie and the Infinite Sadness", "label": "Virgin", "year": 1996, "tags": ["90s", "alternative", "rock"]},
  {"id": "NOG3eus4ZSo", "artist": "The Smashing Pumpkins", "title": "Tonight, Tonight", "album": "Mellon Collie and the Infinite Sadness", "label": "Virgin", "year": 1996, "tags": ["90s", "alternative", "rock"]},
  {"id": "GLvohMXgcBo", "artist": "Red Hot Chili Peppers", "title": "Under the Bridge", "album": "Blood Sugar Sex Magik", "label": "Warner Bros.", "year": 1992, "tags": ["90s", "alternative", "rock", "funk"]},
  {"id": "Mr_uHJPUlO8", "artist": "Red Hot Chili Peppers", "title": "Give It Away", "album": "Blood Sugar Sex Magik", "label": "Warner Bros.", "year": 1991, "tags": ["90s", "alternative", "rock", "funk"]},
  {"id": "eBG7P-K-r1Y", "artist": "Foo Fighters", "title": "Everlong", "album": "The Colour and the Shape", "label": "Roswell / Capitol", "year": 1997, "tags": ["90s", "alternative", "rock"]},
  {"id": "pLdJQFTnZfA", "artist": "Foo Fighters", "title": "Big Me", "album": "Foo Fighters", "label": "Roswell / Capitol", "year": 1996, "tags": ["90s", "alternative", "rock"]},
  {"id": "NUTGr5t3MoY", "artist": "Green Day", "title": "Basket Case", "album": "Dookie", "label": "Reprise", "year": 1994, "tags": ["90s", "punk", "alternative", "rock"]},
  {"id": "kemivUKb4f4", "artist": "Weezer", "title": "Buddy Holly", "album": "Weezer", "label": "DGC", "year": 1994, "tags": ["90s", "alternative", "rock", "indie"]},
  {"id": "YgSPaXgAdzE", "artist": "Beck", "title": "Loser", "album": "Mellow Gold", "label": "DGC", "year": 1994, "tags": ["90s", "alternative", "indie"]},
  {"id": "O3dWBLoU--E", "artist": "Hole", "title": "Celebrity Skin", "album": "Celebrity Skin", "label": "DGC", "year": 1998, "tags": ["90s", "alternative", "rock", "grunge"]},
  {"id": "aZdTSGEoiDc", "artist": "Bush", "title": "Glycerine", "album": "Sixteen Stone", "label": "Trauma / Interscope", "year": 1995, "tags": ["90s", "grunge", "alternative", "rock"]},
  {"id": "xsJ4O-nSveg", "artist": "Live", "title": "Lightning Crashes", "album": "Throwing Copper", "label": "Radioactive", "year": 1994, "tags": ["90s", "alternative", "rock"]},
  {"id": "YuK7UVq05Ek", "artist": "Alanis Morissette", "title": "Ironic", "album": "Jagged Little Pill", "label": "Maverick", "year": 1996, "tags": ["90s", "alternative", "pop", "rock"]},
  {"id": "6Ejga4kJUts", "artist": "The Cranberries", "title": "Zombie", "album": "No Need to Argue", "label": "Island", "year": 1994, "tags": ["90s", "alternative", "rock"]},
  {"id": "TR3Vdo5etCQ", "artist": "No Doubt", "title": "Don't Speak", "album": "Tragic Kingdom", "label": "Trauma / Interscope", "year": 1996, "tags": ["90s", "alternative", "pop", "rock"]},
  {"id": "O9eNTgAuMls", "artist": "Garbage", "title": "Stupid Girl", "album": "Garbage", "label": "Almo Sounds", "year": 1996, "tags": ["90s", "alternative", "rock", "electronic"]},
  {"id": "AEYN5w4T_aM", "artist": "Sublime", "title": "Santeria", "album": "Sublime", "label": "Gasoline Alley / MCA", "year": 1997, "tags": ["90s", "alternative", "ska", "rock"]},
  {"id": "beINamVRGy4", "artist": "Third Eye Blind", "title": "Semi-Charmed Life", "album": "Third Eye Blind", "label": "Elektra", "year": 1997, "tags": ["90s", "alternative", "pop", "rock"]},
  {"id": "K7l5ZeVVoCA", "artist": "Blink-182", "title": "What's My Age Again?", "album": "Enema of the State", "label": "MCA", "year": 1999, "tags": ["90s", "punk", "pop", "rock"]},
  {"id": "QtTR-_Klcq8", "artist": "The Offspring", "title": "Pretty Fly (For a White Guy)", "album": "Americana", "label": "Columbia", "year": 1998, "tags": ["90s", "punk", "rock"]},
  {"id": "F_HoMkkRHv8", "artist": "Cake", "title": "The Distance", "album": "Fashion Nugget", "label": "Capricorn", "year": 1996, "tags": ["90s", "alternative", "indie"]},
  {"id": "3L4YrGaR8E4", "artist": "Rage Against the Machine", "title": "Bulls on Parade", "album": "Evil Empire", "label": "Epic", "year": 1996, "tags": ["90s", "metal", "rock", "hip-hop"]},
  {"id": "8To61f_JZ34", "artist": "Radiohead", "title": "Karma Police", "album": "OK Computer", "label": "Capitol", "year": 1997, "tags": ["90s", "alternative", "indie", "britpop"]},
  {"id": "4jRqVa9TgMM", "artist": "Radiohead", "title": "Creep", "album": "Pablo Honey", "label": "Capitol", "year": 1993, "tags": ["90s", "alternative", "indie", "britpop"]},
  {"id": "ofO827Zq5b8", "artist": "Radiohead", "title": "Paranoid Android", "album": "OK Computer", "label": "Capitol", "year": 1997, "tags": ["90s", "alternative", "indie", "art-rock"]},
  {"id": "SSbBvKaM6sk", "artist": "Blur", "title": "Song 2", "album": "Blur", "label": "Virgin", "year": 1997, "tags": ["90s", "britpop", "alternative", "rock"]},
  {"id": "6oqXVx3sBOk", "artist": "Blur", "title": "Coffee & TV", "album": "13", "label": "Virgin", "year": 1999, "tags": ["90s", "britpop", "indie"]},
  {"id": "bx1Bh8ZvH84", "artist": "Oasis", "title": "Wonderwall", "album": "(What's the Story) Morning Glory?", "label": "Epic", "year": 1995, "tags": ["90s", "britpop", "rock"]},
  {"id": "yuTMWgOduFM", "artist": "Pulp", "title": "Common People", "album": "Different Class", "label": "Island", "year": 1995, "tags": ["90s", "britpop", "indie"]},
  {"id": "Lntdr13ZuhU", "artist": "The Verve", "title": "Bitter Sweet Symphony", "album": "Urban Hymns", "label": "Virgin", "year": 1997, "tags": ["90s", "britpop", "rock"]},
  {"id": "K47QUe01-3Y", "artist": "Björk", "title": "It's Oh So Quiet", "album": "Post", "label": "Elektra", "year": 1995, "tags": ["90s", "art-pop", "indie"]},
  {"id": "EjzIsA0l30o", "artist": "Björk", "title": "Human Behaviour", "album": "Debut", "label": "Elektra", "year": 1993, "tags": ["90s", "art-pop", "electronic"]},
  {"id": "z5rRZdiu1UE", "artist": "Beastie Boys", "title": "Sabotage", "album": "Ill Communication", "label": "Grand Royal / Capitol", "year": 1994, "tags": ["90s", "hip-hop", "punk", "alternative"]},
  {"id": "DO0Q334X-6E", "artist": "Beastie Boys", "title": "Intergalactic", "album": "Hello Nasty", "label": "Grand Royal / Capitol", "year": 1998, "tags": ["90s", "hip-hop", "alternative"]},
  {"id": "tPgf_btTFlc", "artist": "Pixies", "title": "Here Comes Your Man", "album": "Doolittle", "label": "4AD / Elektra", "year": 1989, "tags": ["80s", "indie", "alternative"]},
  {"id": "fxvkI9MTQw4", "artist": "The Breeders", "title": "Cannonball", "album": "Last Splash", "label": "4AD / Elektra", "year": 1993, "tags": ["90s", "indie", "alternative"]},
  {"id": "SDTSUwIZdMk", "artist": "Sonic Youth", "title": "Kool Thing", "album": "Goo", "label": "DGC", "year": 1990, "tags": ["90s", "indie", "alternative", "noise"]},
  {"id": "QTTgpTeb0Z8", "artist": "Pavement", "title": "Cut Your Hair", "album": "Crooked Rain, Crooked Rain", "label": "Matador", "year": 1994, "tags": ["90s", "indie", "alternative"]},
  {"id": "xwtdhWltSIg", "artist": "R.E.M.", "title": "Losing My Religion", "album": "Out of Time", "label": "Warner Bros.", "year": 1991, "tags": ["90s", "alternative", "rock"]},
  {"id": "aGSKrC7dGcY", "artist": "Depeche Mode", "title": "Enjoy the Silence", "album": "Violator", "label": "Sire / Reprise", "year": 1990, "tags": ["90s", "synth-pop", "alternative"]},
  {"id": "mGgMZpGYiy8", "artist": "The Cure", "title": "Friday I'm in Love", "album": "Wish", "label": "Fiction / Elektra", "year": 1992, "tags": ["90s", "alternative", "goth", "pop"]},
  {"id": "BzUnqr1t7yI", "artist": "Jane's Addiction", "title": "Been Caught Stealing", "album": "Ritual de lo Habitual", "label": "Warner Bros.", "year": 1990, "tags": ["90s", "alternative", "rock"]},
  {"id": "iMU0cl-qbEc", "artist": "Portishead", "title": "Sour Times", "album": "Dummy", "label": "Go! Beat / London", "year": 1994, "tags": ["90s", "trip-hop", "electronic"]},
  {"id": "u7K72X4eo_s", "artist": "Massive Attack", "title": "Teardrop", "album": "Mezzanine", "label": "Virgin", "year": 1998, "tags": ["90s", "trip-hop", "electronic"]},
  {"id": "ENXvZ9YRjbo", "artist": "Weezer", "title": "Say It Ain't So", "album": "Weezer", "label": "DGC", "year": 1995, "tags": ["90s", "alternative", "indie", "rock"]},
  {"id": "0-EF60neguk", "artist": "Sinéad O'Connor", "title": "Nothing Compares 2 U", "album": "I Do Not Want What I Haven't Got", "label": "Ensign / Chrysalis", "year": 1990, "tags": ["90s", "pop", "alternative"]},
  {"id": "4JkIs37a2JE", "artist": "Jamiroquai", "title": "Virtual Insanity", "album": "Travelling Without Moving", "label": "Work", "year": 1996, "tags": ["90s", "funk", "pop", "acid-jazz"]},
  {"id": "FFOzayDpWoI", "artist": "Fiona Apple", "title": "Criminal", "album": "Tidal", "label": "Clean Slate / Work", "year": 1997, "tags": ["90s", "alternative", "pop"]},
  {"id": "V2yy141q8HQ", "artist": "Eels", "title": "Novocaine for the Soul", "album": "Beautiful Freak", "label": "DreamWorks", "year": 1996, "tags": ["90s", "indie", "alternative"]},
  {"id": "ilKcXIFi-Rc", "artist": "Elastica", "title": "Connection", "album": "Elastica", "label": "DGC", "year": 1994, "tags": ["90s", "britpop", "punk", "indie"]},
  {"id": "qUE4oDunYkc", "artist": "Supergrass", "title": "Alright", "album": "I Should Coco", "label": "Parlophone / Capitol", "year": 1995, "tags": ["90s", "britpop", "indie"]},
  {"id": "NI6aOFI7hms", "artist": "The Cardigans", "title": "Lovefool", "album": "First Band on the Moon", "label": "Stockholm / Mercury", "year": 1996, "tags": ["90s", "pop", "indie"]},
  {"id": "4B_UYYPb-Gk", "artist": "Run-DMC", "title": "Walk This Way", "album": "Raising Hell", "label": "Profile", "year": 1986, "tags": ["80s", "hip-hop", "rock"]},
  {"id": "mmo3HFa2vjg", "artist": "Public Enemy", "title": "Fight the Power", "album": "Fear of a Black Planet", "label": "Def Jam", "year": 1989, "tags": ["80s", "hip-hop"]},
  {"id": "eBShN8qT4lk", "artist": "Beastie Boys", "title": "(You Gotta) Fight for Your Right (To Party)", "album": "Licensed to Ill", "label": "Def Jam / Columbia", "year": 1986, "tags": ["80s", "hip-hop", "rock"]},
  {"id": "Q6TLWqn82J4", "artist": "A Tribe Called Quest", "title": "Scenario", "album": "The Low End Theory", "label": "Jive", "year": 1992, "tags": ["90s", "hip-hop"]},
  {"id": "8GliyDgAGQI", "artist": "Dr. Dre", "title": "Nuthin' but a 'G' Thang", "album": "The Chronic", "label": "Death Row / Interscope", "year": 1992, "tags": ["90s", "hip-hop", "g-funk"]},
  {"id": "KyKepKFoA0I", "artist": "Snoop Dogg", "title": "Gin and Juice", "album": "Doggystyle", "label": "Death Row / Interscope", "year": 1994, "tags": ["90s", "hip-hop", "g-funk"]},
  {"id": "_JZom_gVfuw", "artist": "The Notorious B.I.G.", "title": "Juicy", "album": "Ready to Die", "label": "Bad Boy / Arista", "year": 1994, "tags": ["90s", "hip-hop"]},
  {"id": "glEiPXAYE-U", "artist": "The Notorious B.I.G.", "title": "Hypnotize", "album": "Life After Death", "label": "Bad Boy / Arista", "year": 1997, "tags": ["90s", "hip-hop"]},
  {"id": "N0VdRLdg2ng", "artist": "2Pac", "title": "California Love", "album": "All Eyez on Me", "label": "Death Row / Interscope", "year": 1995, "tags": ["90s", "hip-hop", "g-funk"]},
  {"id": "PBwAxmrE194", "artist": "Wu-Tang Clan", "title": "C.R.E.A.M.", "album": "Enter the Wu-Tang (36 Chambers)", "label": "Loud / RCA", "year": 1994, "tags": ["90s", "hip-hop"]},
  {"id": "e5PnuIRnJW8", "artist": "Nas", "title": "The World Is Yours", "album": "Illmatic", "label": "Columbia", "year": 1994, "tags": ["90s", "hip-hop"]},
  {"id": "RijB8wnJCN0", "artist": "Cypress Hill", "title": "Insane in the Brain", "album": "Black Sunday", "label": "Ruffhouse / Columbia", "year": 1993, "tags": ["90s", "hip-hop"]},
  {"id": "jrL_LzX5wv4", "artist": "House of Pain", "title": "Jump Around", "album": "House of Pain", "label": "Tommy Boy", "year": 1992, "tags": ["90s", "hip-hop"]},
  {"id": "SQCSxqScSVQ", "artist": "Coolio", "title": "Gangsta's Paradise", "album": "Gangsta's Paradise", "label": "Tommy Boy", "year": 1995, "tags": ["90s", "hip-hop"]},
  {"id": "hHcyJPTTn9w", "artist": "Missy Elliott", "title": "The Rain (Supa Dupa Fly)", "album": "Supa Dupa Fly", "label": "The Goldmind / EastWest", "year": 1997, "tags": ["90s", "hip-hop", "r&b"]},
  {"id": "EQzvQO2LcA4", "artist": "Busta Rhymes", "title": "Woo Hah!! Got You All in Check", "album": "The Coming", "label": "Elektra", "year": 1996, "tags": ["90s", "hip-hop"]},
  {"id": "aIXyKmElvv8", "artist": "Fugees", "title": "Ready or Not", "album": "The Score", "label": "Ruffhouse / Columbia", "year": 1996, "tags": ["90s", "hip-hop", "r&b"]},
  {"id": "T6QKqFPRZSA", "artist": "Lauryn Hill", "title": "Doo Wop (That Thing)", "album": "The Miseducation of Lauryn Hill", "label": "Ruffhouse / Columbia", "year": 1998, "tags": ["90s", "hip-hop", "r&b"]},
  {"id": "drsQLEU0N1Y", "artist": "OutKast", "title": "Rosa Parks", "album": "Aquemini", "label": "LaFace / Arista", "year": 1998, "tags": ["90s", "hip-hop"]},
  {"id": "vCadcBR95oU", "artist": "Salt-N-Pepa", "title": "Push It", "album": "Hot, Cool & Vicious", "label": "Next Plateau", "year": 1987, "tags": ["80s", "hip-hop"]},
  {"id": "i8tUWVowN0g", "artist": "MC Hammer", "title": "U Can't Touch This", "album": "Please Hammer, Don't Hurt 'Em", "label": "Capitol", "year": 1990, "tags": ["90s", "hip-hop", "pop"]},
  {"id": "7f7FuDagYLU", "artist": "Naughty by Nature", "title": "O.P.P.", "album": "Naughty by Nature", "label": "Tommy Boy", "year": 1991, "tags": ["90s", "hip-hop"]},
  {"id": "3JcmQONgXJM", "artist": "Will Smith", "title": "Gettin' Jiggy Wit It", "album": "Big Willie Style", "label": "Columbia", "year": 1998, "tags": ["90s", "hip-hop", "pop"]},
  {"id": "NKMtZm2YuBE", "artist": "Puff Daddy & Faith Evans", "title": "I'll Be Missing You", "album": "No Way Out", "label": "Bad Boy / Arista", "year": 1997, "tags": ["90s", "hip-hop", "r&b"]},
  {"id": "wFFQ-JAm580", "artist": "Jay-Z", "title": "Hard Knock Life (Ghetto Anthem)", "album": "Vol. 2... Hard Knock Life", "label": "Roc-A-Fella / Def Jam", "year": 1998, "tags": ["90s", "hip-hop"]},
  {"id": "ThlhSnRk21E", "artist": "DMX", "title": "Ruff Ryders' Anthem", "album": "It's Dark and Hell Is Hot", "label": "Ruff Ryders / Def Jam", "year": 1998, "tags": ["90s", "hip-hop"]},
  {"id": "sNPnbI1arSE", "artist": "Eminem", "title": "My Name Is", "album": "The Slim Shady LP", "label": "Aftermath / Interscope", "year": 1999, "tags": ["90s", "hip-hop"]},
  {"id": "PBsjggc5jHM", "artist": "Digital Underground", "title": "The Humpty Dance", "album": "Sex Packets", "label": "Tommy Boy", "year": 1990, "tags": ["90s", "hip-hop", "funk"]},
  {"id": "vimZj8HW0Kg", "artist": "LL Cool J", "title": "Mama Said Knock You Out", "album": "Mama Said Knock You Out", "label": "Def Jam", "year": 1990, "tags": ["90s", "hip-hop"]},
  {"id": "wqVsfGQ_1SU", "artist": "The Pharcyde", "title": "Drop", "album": "Labcabincalifornia", "label": "Delicious Vinyl", "year": 1995, "tags": ["90s", "hip-hop"]},
  {"id": "CD-E-LDc384", "artist": "Metallica", "title": "Enter Sandman", "album": "Metallica", "label": "Elektra", "year": 1991, "tags": ["90s", "metal", "rock"]},
  {"id": "WM8bTdBs-cw", "artist": "Metallica", "title": "One", "album": "...And Justice for All", "label": "Elektra", "year": 1989, "tags": ["80s", "metal", "rock"]},
  {"id": "1w7OgIMMRc4", "artist": "Guns N' Roses", "title": "Sweet Child O' Mine", "album": "Appetite for Destruction", "label": "Geffen", "year": 1987, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "YJfKBMmcSus", "artist": "Guns N' Roses", "title": "November Rain", "album": "Use Your Illusion I", "label": "Geffen", "year": 1992, "tags": ["90s", "hair-metal", "rock"]},
  {"id": "U1lTNjooUYE", "artist": "Guns N' Roses", "title": "Welcome to the Jungle", "album": "Appetite for Destruction", "label": "Geffen", "year": 1987, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "v2AC41dglnM", "artist": "AC/DC", "title": "Thunderstruck", "album": "The Razors Edge", "label": "Atco", "year": 1990, "tags": ["90s", "rock", "metal"]},
  {"id": "AkFqg5wAuFk", "artist": "Pantera", "title": "Walk", "album": "Vulgar Display of Power", "label": "Atco / EastWest", "year": 1992, "tags": ["90s", "metal"]},
  {"id": "PTFwQP86BRs", "artist": "Nine Inch Nails", "title": "Closer", "album": "The Downward Spiral", "label": "Nothing / Interscope", "year": 1994, "tags": ["90s", "industrial", "alternative"]},
  {"id": "Ypkv0HeUvTc", "artist": "Marilyn Manson", "title": "The Beautiful People", "album": "Antichrist Superstar", "label": "Nothing / Interscope", "year": 1996, "tags": ["90s", "industrial", "metal"]},
  {"id": "bWXazVhlyxQ", "artist": "Rage Against the Machine", "title": "Killing in the Name", "album": "Rage Against the Machine", "label": "Epic", "year": 1992, "tags": ["90s", "metal", "rock", "hip-hop"]},
  {"id": "jRGrNDV2mKc", "artist": "Korn", "title": "Freak on a Leash", "album": "Follow the Leader", "label": "Immortal / Epic", "year": 1999, "tags": ["90s", "nu-metal", "metal"]},
  {"id": "nspxAG12Cpc", "artist": "Tool", "title": "Sober", "album": "Undertow", "label": "Zoo", "year": 1993, "tags": ["90s", "metal", "alternative"]},
  {"id": "ZG_k5CSYKhg", "artist": "Faith No More", "title": "Epic", "album": "The Real Thing", "label": "Slash / Reprise", "year": 1990, "tags": ["90s", "metal", "alternative", "funk"]},
  {"id": "E0E0ynyIUsg", "artist": "White Zombie", "title": "More Human than Human", "album": "Astro-Creep: 2000", "label": "Geffen", "year": 1995, "tags": ["90s", "metal", "industrial"]},
  {"id": "EqQuihD0hoI", "artist": "Rob Zombie", "title": "Dragula", "album": "Hellbilly Deluxe", "label": "Geffen", "year": 1998, "tags": ["90s", "metal", "industrial"]},
  {"id": "h2LG7JXK5mQ", "artist": "Megadeth", "title": "Symphony of Destruction", "album": "Countdown to Extinction", "label": "Capitol", "year": 1992, "tags": ["90s", "metal"]},
  {"id": "XOzs1FehYOA", "artist": "Deftones", "title": "My Own Summer (Shove It)", "album": "Around the Fur", "label": "Maverick", "year": 1997, "tags": ["90s", "nu-metal", "metal", "alternative"]},
  {"id": "GXCh9OhDiCI", "artist": "Ministry", "title": "Jesus Built My Hotrod", "album": "Psalm 69", "label": "Sire / Warner Bros.", "year": 1991, "tags": ["90s", "industrial", "metal"]},
  {"id": "0UIB9Y4OFPs", "artist": "Def Leppard", "title": "Pour Some Sugar on Me", "album": "Hysteria", "label": "Mercury", "year": 1987, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "CmXWkMlKFkI", "artist": "Mötley Crüe", "title": "Kickstart My Heart", "album": "Dr. Feelgood", "label": "Elektra", "year": 1989, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "Qq4j1LtCdww", "artist": "Alice Cooper", "title": "Poison", "album": "Trash", "label": "Epic", "year": 1989, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "5vBGOrI6yBk", "artist": "System of a Down", "title": "Sugar", "album": "System of a Down", "label": "American / Columbia", "year": 1999, "tags": ["90s", "nu-metal", "metal"]},
  {"id": "JTMVOzPPtiw", "artist": "Limp Bizkit", "title": "Nookie", "album": "Significant Other", "label": "Flip / Interscope", "year": 1999, "tags": ["90s", "nu-metal", "metal"]},
  {"id": "vFwYJYl5GUQ", "artist": "Type O Negative", "title": "Black No. 1", "album": "Bloody Kisses", "label": "Roadrunner", "year": 1993, "tags": ["90s", "goth", "metal"]},
  {"id": "Ghd2bkIadG4", "artist": "Skid Row", "title": "18 and Life", "album": "Skid Row", "label": "Atlantic", "year": 1989, "tags": ["80s", "hair-metal", "rock"]},
  {"id": "86URGgqONvA", "artist": "Iron Maiden", "title": "Run to the Hills", "album": "The Number of the Beast", "label": "EMI", "year": 1982, "tags": ["80s", "metal"]},
  {"id": "4fndeDfaWCg", "artist": "Backstreet Boys", "title": "I Want It That Way", "album": "Millennium", "label": "Jive", "year": 1999, "tags": ["90s", "pop", "boy-band"]},
  {"id": "M6-A6sAaWUg", "artist": "Backstreet Boys", "title": "Everybody (Backstreet's Back)", "album": "Backstreet's Back", "label": "Jive", "year": 1997, "tags": ["90s", "pop", "boy-band"]},
  {"id": "C-u5WLJ9Yk4", "artist": "Britney Spears", "title": "...Baby One More Time", "album": "...Baby One More Time", "label": "Jive", "year": 1998, "tags": ["90s", "pop"]},
  {"id": "KUer_Y-0tsg", "artist": "Britney Spears", "title": "(You Drive Me) Crazy", "album": "...Baby One More Time", "label": "Jive", "year": 1999, "tags": ["90s", "pop"]},
  {"id": "_ZcmuKsyvzg", "artist": "*NSYNC", "title": "Tearin' Up My Heart", "album": "*NSYNC", "label": "RCA", "year": 1997, "tags": ["90s", "pop", "boy-band"]},
  {"id": "kIDWgqDBNXA", "artist": "Christina Aguilera", "title": "Genie in a Bottle", "album": "Christina Aguilera", "label": "RCA", "year": 1999, "tags": ["90s", "pop"]},
  {"id": "gJLIiF15wjQ", "artist": "Spice Girls", "title": "Wannabe", "album": "Spice", "label": "Virgin", "year": 1996, "tags": ["90s", "pop"]},
  {"id": "9ro0FW9Qt-4", "artist": "Spice Girls", "title": "Say You'll Be There", "album": "Spice", "label": "Virgin", "year": 1996, "tags": ["90s", "pop"]},
  {"id": "p47fEXGabaY", "artist": "Ricky Martin", "title": "Livin' la Vida Loca", "album": "Ricky Martin", "label": "C2 / Columbia", "year": 1999, "tags": ["90s", "pop", "latin"]},
  {"id": "nZXRV4MezEw", "artist": "Cher", "title": "Believe", "album": "Believe", "label": "Warner Bros.", "year": 1998, "tags": ["90s", "pop", "dance"]},
  {"id": "NHozn0YXAeE", "artist": "Hanson", "title": "MMMBop", "album": "Middle of Nowhere", "label": "Mercury", "year": 1997, "tags": ["90s", "pop"]},
  {"id": "ZyhrYis509A", "artist": "Aqua", "title": "Barbie Girl", "album": "Aquarium", "label": "MCA", "year": 1997, "tags": ["90s", "pop", "eurodance"]},
  {"id": "2H5uWRjFsGc", "artist": "Chumbawamba", "title": "Tubthumping", "album": "Tubthumper", "label": "Republic / Universal", "year": 1997, "tags": ["90s", "pop", "rock"]},
  {"id": "Z9aaaA7Bqes", "artist": "Smash Mouth", "title": "All Star", "album": "Astro Lounge", "label": "Interscope", "year": 1999, "tags": ["90s", "pop", "rock"]},
  {"id": "fC_q9KPczAg", "artist": "Barenaked Ladies", "title": "One Week", "album": "Stunt", "label": "Reprise", "year": 1998, "tags": ["90s", "pop", "rock"]},
  {"id": "VV1XWJN3nJo", "artist": "Natalie Imbruglia", "title": "Torn", "album": "Left of the Middle", "label": "RCA", "year": 1997, "tags": ["90s", "pop"]},
  {"id": "R88DKYQFKvM", "artist": "Céline Dion", "title": "My Heart Will Go On", "album": "Let's Talk About Love", "label": "550 Music / Epic", "year": 1997, "tags": ["90s", "pop", "ballad"]},
  {"id": "lYfkl-HXfuU", "artist": "Jennifer Lopez", "title": "If You Had My Love", "album": "On the 6", "label": "Work / Epic", "year": 1999, "tags": ["90s", "pop", "r&b"]},
  {"id": "HQt6jIKNwgU", "artist": "Savage Garden", "title": "I Want You", "album": "Savage Garden", "label": "Columbia", "year": 1996, "tags": ["90s", "pop"]},
  {"id": "iqu132vTl5Y", "artist": "Ace of Base", "title": "The Sign", "album": "The Sign", "label": "Arista", "year": 1993, "tags": ["90s", "pop", "eurodance"]},
  {"id": "3JWTaaS7LdU", "artist": "Whitney Houston", "title": "I Will Always Love You", "album": "The Bodyguard", "label": "Arista", "year": 1992, "tags": ["90s", "pop", "ballad", "r&b"]},
  {"id": "Fl6NKQktuYw", "artist": "Mariah Carey", "title": "Fantasy", "album": "Daydream", "label": "Columbia", "year": 1995, "tags": ["90s", "pop", "r&b"]},
  {"id": "GuJQSAiODqI", "artist": "Madonna", "title": "Vogue", "album": "I'm Breathless", "label": "Sire / Warner Bros.", "year": 1990, "tags": ["90s", "pop", "dance"]},
  {"id": "Jnq9wPDoDKg", "artist": "Sixpence None the Richer", "title": "Kiss Me", "album": "Sixpence None the Richer", "label": "Squint", "year": 1998, "tags": ["90s", "pop", "indie"]},
  {"id": "wpyjDrRfDAU", "artist": "Sugar Ray", "title": "Every Morning", "album": "14:59", "label": "Lava / Atlantic", "year": 1999, "tags": ["90s", "pop", "rock"]},
  {"id": "66eIiJPgIhk", "artist": "Len", "title": "Steal My Sunshine", "album": "You Can't Stop the Bum Rush", "label": "Work", "year": 1999, "tags": ["90s", "pop", "indie"]},
  {"id": "CEexzfooPGE", "artist": "Eiffel 65", "title": "Blue (Da Ba Dee)", "album": "Europop", "label": "Republic / Universal", "year": 1999, "tags": ["90s", "eurodance", "pop"]},
  {"id": "EK_LN3XEcnw", "artist": "Lou Bega", "title": "Mambo No. 5", "album": "A Little Bit of Mambo", "label": "RCA", "year": 1999, "tags": ["90s", "pop", "latin"]},
  {"id": "xGytDsqkQY8", "artist": "Semisonic", "title": "Closing Time", "album": "Feeling Strangely Fine", "label": "MCA", "year": 1998, "tags": ["90s", "pop", "rock", "alternative"]},
  {"id": "Wjg5A9VtnIE", "artist": "Goo Goo Dolls", "title": "Iris", "album": "Dizzy Up the Girl", "label": "Warner Bros.", "year": 1998, "tags": ["90s", "pop", "rock", "ballad"]},
  {"id": "wmin5WkOuPw", "artist": "The Prodigy", "title": "Firestarter", "album": "The Fat of the Land", "label": "XL / Maverick", "year": 1996, "tags": ["90s", "electronic", "big-beat"]},
  {"id": "6_PAHbqq-o4", "artist": "The Prodigy", "title": "Breathe", "album": "The Fat of the Land", "label": "XL / Maverick", "year": 1996, "tags": ["90s", "electronic", "big-beat"]},
  {"id": "iTxOKsyZ0Lw", "artist": "The Chemical Brothers", "title": "Block Rockin' Beats", "album": "Dig Your Own Hole", "label": "Astralwerks / Virgin", "year": 1997, "tags": ["90s", "electronic", "big-beat"]},
  {"id": "K0HSD_i2DvA", "artist": "Daft Punk", "title": "Around the World", "album": "Homework", "label": "Virgin", "year": 1997, "tags": ["90s", "electronic", "house"]},
  {"id": "mmi60Bd4jSs", "artist": "Daft Punk", "title": "Da Funk", "album": "Homework", "label": "Virgin", "year": 1995, "tags": ["90s", "electronic", "house"]},
  {"id": "ruAi4VBoBSM", "artist": "Fatboy Slim", "title": "Praise You", "album": "You've Come a Long Way, Baby", "label": "Skint / Astralwerks", "year": 1999, "tags": ["90s", "electronic", "big-beat"]},
  {"id": "t01E5q1Lny8", "artist": "Underworld", "title": "Born Slippy .NUXX", "album": "Trainspotting (Soundtrack)", "label": "Junior Boy's Own", "year": 1996, "tags": ["90s", "electronic", "techno"]},
  {"id": "yJnve05CnNE", "artist": "Orbital", "title": "The Box", "album": "In Sides", "label": "Internal / FFRR", "year": 1996, "tags": ["90s", "electronic", "techno"]},
  {"id": "NLCHARjjrws", "artist": "Moby", "title": "Go", "album": "Moby", "label": "Instinct", "year": 1991, "tags": ["90s", "electronic", "techno"]},
  {"id": "SJyhZ-3Z8A8", "artist": "Basement Jaxx", "title": "Red Alert", "album": "Remedy", "label": "XL / Astralwerks", "year": 1999, "tags": ["90s", "electronic", "house"]},
  {"id": "FQlAEiCb8m0", "artist": "Stardust", "title": "Music Sounds Better with You", "album": "Music Sounds Better with You", "label": "Roulé / Virgin", "year": 1998, "tags": ["90s", "electronic", "house"]},
  {"id": "aGHv1LD2EM4", "artist": "Björk", "title": "Army of Me", "album": "Post", "label": "Elektra", "year": 1995, "tags": ["90s", "electronic", "art-pop"]},
  {"id": "cgyw6rDFYO8", "artist": "Massive Attack", "title": "Unfinished Sympathy", "album": "Blue Lines", "label": "Wild Bunch / Virgin", "year": 1991, "tags": ["90s", "trip-hop", "electronic"]},
  {"id": "k7O4oM5fHEw", "artist": "Armand Van Helden", "title": "U Don't Know Me", "album": "2Future4U", "label": "Armed / FFRR", "year": 1999, "tags": ["90s", "electronic", "house"]},
  {"id": "U56Ns66Qrb8", "artist": "Everything but the Girl", "title": "Missing", "album": "Amplified Heart", "label": "Atlantic", "year": 1995, "tags": ["90s", "electronic", "house", "pop"]},
  {"id": "8WEtxJ4-sh4", "artist": "TLC", "title": "Waterfalls", "album": "CrazySexyCool", "label": "LaFace / Arista", "year": 1995, "tags": ["90s", "r&b", "hip-hop"]},
  {"id": "FrLequ6dUdM", "artist": "TLC", "title": "No Scrubs", "album": "FanMail", "label": "LaFace / Arista", "year": 1999, "tags": ["90s", "r&b", "pop"]},
  {"id": "sQgd6MccwZc", "artist": "Destiny's Child", "title": "Say My Name", "album": "The Writing's on the Wall", "label": "Columbia", "year": 1999, "tags": ["90s", "r&b", "pop"]},
  {"id": "qSIOp_K5GMw", "artist": "Brandy & Monica", "title": "The Boy Is Mine", "album": "Never Say Never", "label": "Atlantic", "year": 1998, "tags": ["90s", "r&b"]},
  {"id": "uB1D9wWxd2w", "artist": "Mark Morrison", "title": "Return of the Mack", "album": "Return of the Mack", "label": "Atlantic", "year": 1996, "tags": ["90s", "r&b"]},
  {"id": "H_WzjiTzZBA", "artist": "D'Angelo", "title": "Brown Sugar", "album": "Brown Sugar", "label": "EMI", "year": 1995, "tags": ["90s", "r&b", "neo-soul"]}
];
